import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import WalletConnectContextProvider from "@/contexts/WalletConnectContext";

const ibmFont = localFont({ src: "../fonts/ibm2.ttf" });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibmFont.className}>
        <WalletConnectContextProvider>
          {children}
        </WalletConnectContextProvider>
      </body>
    </html>
  );
}
